import { LifeGoal } from '@goal/shared-types';

export const ALL_LIFE_GOALS: LifeGoal[] = [
  {
    id: 'GOAL_AUSBILDUNG',
    title: 'Berufsausbildung abschließen',
    description: 'Schließe eine praxisnahe Ausbildung ab und werde zur gefragten Fachkraft.',
    category: 'EDUCATION',
    targetValue: 1,
    currentValue: 0,
    targetUnit: 'Abschluss',
    isAchieved: false,
    priority: 1,
    conflictHint: 'Erfordert 3 Jahre Ausbildungsvergütung, bringt danach solide Einkommenssicherheit.',
    icon: 'GraduationCap',
  },
  {
    id: 'GOAL_STUDIUM',
    title: 'Hochschulstudium abschließen',
    description: 'Erreiche einen Bachelor-Abschluss an einer Universität oder Fachhochschule.',
    category: 'EDUCATION',
    targetValue: 1,
    currentValue: 0,
    targetUnit: 'Abschluss',
    isAchieved: false,
    priority: 2,
    conflictHint: 'Höherer Zeit- und Lernaufwand in den ersten Jahren, langfristig höhere Gehaltschancen.',
    icon: 'BookOpen',
  },
  {
    id: 'GOAL_NOTGROSCHEN',
    title: 'Notgroschen aufbauen (3 Monatsausgaben)',
    description: 'Lege 3 Monatsausgaben als sichere Liquiditätsreserve auf dem Tagesgeldkonto an.',
    category: 'SECURITY',
    targetValue: 3,
    currentValue: 0,
    targetUnit: 'Monate',
    isAchieved: false,
    priority: 1,
    conflictHint: 'Schützt dich zuverlässig vor teuren Dispokrediten und unvorhersehbaren Schäden.',
    icon: 'ShieldCheck',
  },
  {
    id: 'GOAL_SCHULDENFREI',
    title: 'Schuldenfrei bleiben (außer Immobilie)',
    description: 'Vermeide Konsumkredite und dauerhafte Dispoüberziehungen im Alltag.',
    category: 'SECURITY',
    targetValue: 1,
    currentValue: 1,
    targetUnit: 'Status',
    isAchieved: true,
    priority: 3,
    conflictHint: 'Erfordert Disziplin bei Anschaffungen wie Smartphones, Möbeln oder Reisen.',
    icon: 'PiggyBank',
  },
  {
    id: 'GOAL_EIGENE_WOHNUNG',
    title: 'Erste eigene Wohnung beziehen',
    description: 'Ziehe von den Eltern aus in deine eigene Mietwohnung oder eine WG.',
    category: 'HOUSING',
    targetValue: 1,
    currentValue: 0,
    targetUnit: 'Wohnung',
    isAchieved: false,
    priority: 2,
    conflictHint: 'Erhöht deine monatlichen Fixkosten (Miete, Strom, Internet, Kaution) spürbar.',
    icon: 'Home',
  },
  {
    id: 'GOAL_EIGENHEIM',
    title: 'Eigenheim / Eigentumswohnung erwerben',
    description: 'Kaufe eine Immobilie zur Selbstnutzung mit solidem Eigenkapital.',
    category: 'HOUSING',
    targetValue: 1,
    currentValue: 0,
    targetUnit: 'Immobilie',
    isAchieved: false,
    priority: 3,
    conflictHint: 'Erfordert mind. 15–20 % Eigenkapital und bindet das Budget über 20–30 Jahre.',
    icon: 'Key',
  },
  {
    id: 'GOAL_BAUSPARER',
    title: 'Bausparvertrag zuteilungsreif ansparen',
    description: 'Spare mindestens 40 % der Bausparsumme an, um zinsgünstige Darlehen zu sichern.',
    category: 'SECURITY',
    targetValue: 1,
    currentValue: 0,
    targetUnit: 'Bausparer',
    isAchieved: false,
    priority: 4,
    conflictHint: 'Sichert niedrige Kreditzinsen für spätere Renovierungen oder den Immobilienkauf.',
    icon: 'FileCheck',
  },
  {
    id: 'GOAL_FAMILIE',
    title: 'Familie gründen & Kinder großziehen',
    description: 'Finde eine feste Partnerschaft und gründe eine glückliche Familie.',
    category: 'FAMILY',
    targetValue: 1,
    currentValue: 0,
    targetUnit: 'Familie',
    isAchieved: false,
    priority: 3,
    conflictHint: 'Bereichert das Leben emotional enorm, erfordert aber finanzielle Verantwortung.',
    icon: 'Users',
  },
  {
    id: 'GOAL_AUTO',
    title: 'Eigenes Auto besitzen',
    description: 'Schaffe dir dein erstes eigenes Auto an, um unabhängig mobil zu sein.',
    category: 'LIFESTYLE',
    targetValue: 1,
    currentValue: 0,
    targetUnit: 'Fahrzeug',
    isAchieved: false,
    priority: 4,
    conflictHint: 'Verursacht neben dem Kaufpreis laufende Kosten (Versicherung, Kraftstoff, Reparaturen).',
    icon: 'Car',
  },
  {
    id: 'GOAL_REISEN',
    title: 'Traumreisen erleben (mind. 2)',
    description: 'Erkunde andere Städte oder Länder und sammle wertvolle Lebenserfahrungen.',
    category: 'LIFESTYLE',
    targetValue: 2,
    currentValue: 0,
    targetUnit: 'Reisen',
    isAchieved: false,
    priority: 4,
    conflictHint: 'Steigert deine Lebenszufriedenheit, beansprucht aber dein Erspartes.',
    icon: 'Plane',
  },
  {
    id: 'GOAL_VERMOEGEN_10K',
    title: '10.000 € Vermögen aufbauen',
    description: 'Erreiche ein Netto-Gesamtvermögen von 10.000 € durch Sparen und kluge Geldanlage.',
    category: 'WEALTH',
    targetValue: 10000,
    currentValue: 0,
    targetUnit: '€',
    isAchieved: false,
    priority: 2,
    conflictHint: 'Braucht einen disziplinierten ETF- oder Tagesgeld-Sparplan über mehrere Jahre.',
    icon: 'TrendingUp',
  },
  {
    id: 'GOAL_VERMOEGEN_50K',
    title: '50.000 € Vermögen aufbauen',
    description: 'Erreiche ein Netto-Gesamtvermögen von 50.000 € durch Sparen und kluge Geldanlage.',
    category: 'WEALTH',
    targetValue: 50000,
    currentValue: 0,
    targetUnit: '€',
    isAchieved: false,
    priority: 2,
    conflictHint: 'Braucht einen disziplinierten ETF- oder Tagesgeld-Sparplan über mehrere Jahre.',
    icon: 'TrendingUp',
  },
];
