import { InsuranceContract } from '@goal/shared-types';

export const AVAILABLE_INSURANCES: InsuranceContract[] = [
  {
    id: 'INS_HAFTPFLICHT',
    type: 'HAFTPFLICHT',
    name: 'Privathaftpflicht-Versicherung',
    providerName: 'Secura Guard',
    monthlyPremium: 5,
    coverageLimit: 10000000, // 10 Mio. €
    deductible: 0,
    availableDeductibles: [0, 150, 300],
    waitingPeriodMonthsRemaining: 0,
    initialWaitingPeriodMonths: 0,
    importanceTier: 'ESSENTIAL',
    isActive: false,
    explanation:
      'Absolutes Basismuss! Schützt vor existenzbedrohenden Schadensersatzforderungen nach BGB § 823 (z. B. verursachte Unfälle oder Personenschäden).',
  },
  {
    id: 'INS_BERUFSUNFAEHIGKEIT',
    type: 'BERUFSUNFAEHIGKEIT',
    name: 'Berufsunfähigkeitsversicherung (BU)',
    providerName: 'LebensPlus Vorsorge',
    monthlyPremium: 35,
    coverageLimit: 1500, // Monatliche BU-Rente
    deductible: 0,
    availableDeductibles: [0],
    waitingPeriodMonthsRemaining: 3,
    initialWaitingPeriodMonths: 3,
    importanceTier: 'ESSENTIAL',
    healthPreConditionRequired: true,
    isActive: false,
    explanation:
      'Sichert deine wertvollste Einkommensquelle ab: deine Arbeitskraft. Zahlt eine vertragliche Monatsrente bei Berufsunfähigkeit durch Krankheit oder Burnout.',
  },
  {
    id: 'INS_AUSLANDSKRANKEN',
    type: 'AUSLANDSKRANKEN',
    name: 'Auslandsreisekranken-Versicherung',
    providerName: 'GlobeCare Travel',
    monthlyPremium: 1.5,
    coverageLimit: 1000000,
    deductible: 0,
    availableDeductibles: [0],
    waitingPeriodMonthsRemaining: 0,
    initialWaitingPeriodMonths: 0,
    importanceTier: 'RECOMMENDED',
    isActive: false,
    explanation:
      'Extrem günstig und unverzichtbar bei Reisen! Die gesetzliche Krankenkasse zahlt außerhalb der EU praktisch nichts und übernimmt keinen medizinischen Krankenrücktransport.',
  },
  {
    id: 'INS_ZAHNZUSATZ',
    type: 'ZAHNZUSATZ',
    name: 'Zahnzusatz-Komfortschutz',
    providerName: 'DentCare',
    monthlyPremium: 14,
    coverageLimit: 5000,
    deductible: 0,
    availableDeductibles: [0, 150],
    waitingPeriodMonthsRemaining: 6,
    initialWaitingPeriodMonths: 6,
    importanceTier: 'RECOMMENDED',
    isActive: false,
    explanation:
      'Übernimmt 80–90 % der teuren Eigenanteile bei Zahnersatz, Kronen, Implantaten und professioneller Zahnreinigung.',
  },
  {
    id: 'INS_HAUSRAT',
    type: 'HAUSRAT',
    name: 'Hausrat-Schutz',
    providerName: 'WohnSicher',
    monthlyPremium: 8,
    coverageLimit: 35000,
    deductible: 50,
    availableDeductibles: [0, 150, 300],
    waitingPeriodMonthsRemaining: 0,
    initialWaitingPeriodMonths: 0,
    importanceTier: 'OPTIONAL',
    isActive: false,
    explanation:
      'Ersetzt Wohnungseinrichtung und Wertsachen bei Feuer, Leitungswasser, Sturm, Hagel oder Einbruchdiebstahl zum Neuwert.',
  },
  {
    id: 'INS_RECHTSSCHUTZ',
    type: 'RECHTSSCHUTZ',
    name: 'Privat- & Berufs-Rechtsschutz',
    providerName: 'Justitia Protect',
    monthlyPremium: 18,
    coverageLimit: 300000,
    deductible: 150,
    availableDeductibles: [150, 300],
    waitingPeriodMonthsRemaining: 3,
    initialWaitingPeriodMonths: 3,
    importanceTier: 'OPTIONAL',
    isActive: false,
    explanation:
      'Übernimmt Anwalts- und Gerichtskosten bei Rechtsstreitigkeiten mit Arbeitgebern, Vermietern oder im Straßenverkehr.',
  },
  {
    id: 'INS_KFZ',
    type: 'KFZ_HAFTPFLICHT',
    name: 'Kfz-Haftpflicht & Teilkasko',
    providerName: 'AutoMobil Assekuranz',
    monthlyPremium: 45,
    coverageLimit: 50000000,
    deductible: 150,
    availableDeductibles: [150, 300],
    waitingPeriodMonthsRemaining: 0,
    initialWaitingPeriodMonths: 0,
    importanceTier: 'ESSENTIAL', // Bei Autobesitz gesetzlich vorgeschrieben
    isActive: false,
    explanation:
      'Gesetzliche Pflichtversicherung für jedes zugelassene Kraftfahrzeug. Deckt Personen- und Sachschäden an Dritten.',
  },
  {
    id: 'INS_SMARTPHONE',
    type: 'SMARTPHONE',
    name: 'Smartphone- & Gadget-Versicherung',
    providerName: 'AppSure Tech',
    monthlyPremium: 8.5,
    coverageLimit: 900,
    deductible: 75,
    availableDeductibles: [75],
    waitingPeriodMonthsRemaining: 0,
    initialWaitingPeriodMonths: 0,
    importanceTier: 'QUESTIONABLE',
    isActive: false,
    explanation:
      'Didaktischer Tipp: Häufig überteuert im Verhältnis zum Zeitwertverlust. Oft ist das Bilden eines Notgroschens wirtschaftlich deutlich sinnvoller.',
  },
];
