import { EducationalScenario } from '@goal/shared-types';

export const EDUCATIONAL_SCENARIOS: EducationalScenario[] = [
  {
    id: 'SCENARIO_VOLL',
    title: 'Der volle Lebenslauf (16 bis 67 Jahre)',
    subtitle: 'Vom Schüler bis zum wohlverdienten Ruhestand',
    description:
      'Erlebe 51 Jahre deines Lebens: Ausbildung, erste eigene Wohnung, Partnerschaft, Familie, Vermögensaufbau und Altersvorsorge.',
    icon: 'Sparkles',
    targetAgeRange: '16 – 67 Jahre (51 Jahre)',
    startAge: 16,
    endAge: 67,
    initialCondition: 'FAMILY_SUPPORT',
    focusTopic: 'Ganzheitliche Lebens- und Finanzplanung',
    recommendedGoals: ['GOAL_AUSBILDUNG', 'GOAL_NOTGROSCHEN', 'GOAL_VERMOEGEN_50K'],
  },
  {
    id: 'SCENARIO_AUSBILDUNG',
    title: 'Die Ausbildungs-Challenge (16 bis 22 Jahre)',
    subtitle: 'Unterrichtsmodul: Berufseinstieg & Budgetierung',
    description:
      'Ideal für 45-minütige Schulstunden: Starte mit Ausbildungsvergütung, ziehe in ein WG-Zimmer und baue einen 3-Monats-Notgroschen auf.',
    icon: 'GraduationCap',
    targetAgeRange: '16 – 22 Jahre (6 Jahre)',
    startAge: 16,
    endAge: 22,
    initialCondition: 'FAMILY_SUPPORT',
    focusTopic: '50-30-20-Regel, Ausbildungsvergütung & Notgroschen',
    recommendedGoals: ['GOAL_AUSBILDUNG', 'GOAL_NOTGROSCHEN', 'GOAL_SCHULDENFREI'],
  },
  {
    id: 'SCENARIO_SCHULDENFALLE',
    title: 'Raus aus der Schuldenfalle (18 bis 28 Jahre)',
    subtitle: 'Unterrichtsmodul: Schuldenprävention & Umschuldung',
    description:
      'Du startest mit -1.800 € Disposchulden und 2 BNPL-Ratenkrediten. Schaffe den Turnaround durch Ausgabenstopp, Umschuldung und Budgetdisziplin!',
    icon: 'AlertTriangle',
    targetAgeRange: '18 – 28 Jahre (10 Jahre)',
    startAge: 18,
    endAge: 28,
    initialCondition: 'NO_SUPPORT',
    focusTopic: 'Dispozinsen, Effektivzins, Umschuldung & Schufa',
    recommendedGoals: ['GOAL_SCHULDENFREI', 'GOAL_NOTGROSCHEN', 'GOAL_VERMOEGEN_10K'],
  },
  {
    id: 'SCENARIO_EIGENHEIM',
    title: 'Der Weg zum Eigenheim (25 bis 45 Jahre)',
    subtitle: 'Unterrichtsmodul: Wohnen, Familie & Baufinanzierung',
    description:
      'Vom WG-Zimmer zur Familienimmobilie: Spare Eigenkapital mit Bausparverträgen an, meistere Kaufnebenkosten und sichere deine Familie mit dem 3-Konten-Modell ab.',
    icon: 'Key',
    targetAgeRange: '25 – 45 Jahre (20 Jahre)',
    startAge: 25,
    endAge: 45,
    initialCondition: 'FAMILY_SUPPORT',
    focusTopic: 'Mieten vs. Kaufen, 10 % Kaufnebenkosten & 3-Konten-Modell',
    recommendedGoals: ['GOAL_EIGENHEIM', 'GOAL_FAMILIE', 'GOAL_BAUSPARER'],
  },
  {
    id: 'SCENARIO_VERSICHERUNG',
    title: 'Versichert ins Erwachsenenleben (18 bis 30 Jahre)',
    subtitle: 'Unterrichtsmodul: Haftpflicht, Hausrat & Risikoschutz',
    description:
      'Starte in die erste eigene Lebensphase und entscheide, welche Versicherungen wirklich schützen: Haftpflicht, Hausrat und kleine Policen im Vergleich.',
    icon: 'ShieldCheck',
    targetAgeRange: '18 – 30 Jahre (12 Jahre)',
    startAge: 18,
    endAge: 30,
    initialCondition: 'FAMILY_SUPPORT',
    focusTopic: 'Privathaftpflicht, Hausrat, Selbstbehalt & existenzielle Risiken',
    recommendedGoals: ['GOAL_NOTGROSCHEN', 'GOAL_SCHULDENFREI', 'GOAL_EIGENE_WOHNUNG'],
  },
  {
    id: 'SCENARIO_RENTE_BAV',
    title: 'Rente früh planen: bAV & ETF (30 bis 45 Jahre)',
    subtitle: 'Unterrichtsmodul: Altersvorsorge, Zuschuss & Rentenlücke',
    description:
      'Mitten im Berufsleben vergleichst du gesetzliche Rente, betriebliche Altersvorsorge und eigene Sparpläne, bevor die Rentenlücke zu groß wird.',
    icon: 'PiggyBank',
    targetAgeRange: '30 – 45 Jahre (15 Jahre)',
    startAge: 30,
    endAge: 45,
    initialCondition: 'FAMILY_SUPPORT',
    focusTopic: 'bAV-Arbeitgeberzuschuss, Rentenlücke, ETF-Sparplan & Zinseszins',
    recommendedGoals: ['GOAL_VERMOEGEN_50K', 'GOAL_NOTGROSCHEN', 'GOAL_BAUSPARER'],
  },
  {
    id: 'SCENARIO_STEUERN',
    title: 'Steuern verstehen im Jobstart (20 bis 35 Jahre)',
    subtitle: 'Unterrichtsmodul: Brutto/Netto, Steuerklasse & Lohnsteuer',
    description:
      'Du steigst ins Berufsleben ein und lernst, warum Brutto nicht Netto ist, wie Steuerklassen wirken und welche Entscheidungen dein Monatsbudget verändern.',
    icon: 'Receipt',
    targetAgeRange: '20 – 35 Jahre (15 Jahre)',
    startAge: 20,
    endAge: 35,
    initialCondition: 'CITY_EXPENSIVE',
    focusTopic: 'Brutto-Netto-Rechnung, Lohnsteuer, Sozialabgaben & Steuerklasse',
    recommendedGoals: ['GOAL_AUSBILDUNG', 'GOAL_NOTGROSCHEN', 'GOAL_VERMOEGEN_10K'],
  },
  {
    id: 'SCENARIO_MOBILITAET',
    title: 'Mobil bleiben: ÖPNV oder Auto? (18 bis 28 Jahre)',
    subtitle: 'Unterrichtsmodul: Gesamtkosten, Freiheit & CO2',
    description:
      'Vergleiche Deutschlandticket, eigenes Auto, Finanzierung und laufende Kosten. Finde heraus, wie Mobilität Budget und Lebensqualität prägt.',
    icon: 'Car',
    targetAgeRange: '18 – 28 Jahre (10 Jahre)',
    startAge: 18,
    endAge: 28,
    initialCondition: 'RURAL_CHEAP',
    focusTopic: 'ÖPNV vs. Auto, Total Cost of Ownership, Finanzierung & Rücklagen',
    recommendedGoals: ['GOAL_AUTO', 'GOAL_NOTGROSCHEN', 'GOAL_SCHULDENFREI'],
  },
];
